### PR TITLE
switch "country" label to "Location" and use list from Firefox product

### LINKED ISSUE #227: Switch country/region list to list within Firefox product to avoid political issue
Please change the "Country" to "Country or Region", and switch the list to list within Firefox product here*1, according to this best practice suggestion*2, to avoid any political issues.

1) https://searchfox.org/mozilla-central/source/toolkit/locales/en-US/toolkit/intl/regionNames.ftl 
2) https://wiki.mozilla.org/Lists_of_Countries_and_Regions

### PR DESCRIPTION
**Pull request by irvin**
fix #227

### CODE REVIEW

**Comment by Mte90** [comment]
I need @couci approval for those changes, I will fix also the code conflicts

**Comment by irvin** [comment]
I saw that we use Location in events & groups, so changed from "Country / Region" to "Location" and fixed another two places that had "Country".

**Comment by irvin** [comment]
@Mte90 I had tried rebase the current develop branch

**Comment by Mte90** [comment]
I can see that now is only the label changed, the country names are not changed, if for @couci is fine I will approve it.

**Comment by couci** [comment]
I am getting confused, I see now we use on the portal "Location" on events, profiles and search so is this for something else? And what is the difference on the new country list provided?

**Comment by irvin** [comment]
> I am getting confused, I see now we use on the portal "Location" on events, profiles and search so is this for something else?

Yes I found three more places with “Country” label: group create, group edit and profile edit. 

The country list had fixed so this don’t change it anymore.

**Comment by couci** [comment]
ok @Mte90 I approve this you can go ahead and merge

**Pull request merged**
