### PR TITLE
Feature/moz 343 unsubscribe user

### PR DESCRIPTION
**Pull request by kycapstick**

### CODE REVIEW

**Comment by kycapstick** [comment]
Re-factored this PR to match the patter you're using in the other calls. 

If the member's email exists on the list, the API call will return an object with the member's details, even if the member has already unsubscribed. This object should have a status of "unsubscribed". 

If the member's email does not exist on the campaign list it will return an object with a status of 404. 

Right now, I'm pulling the ID off of the full campaign object stored in the campaign's metadata and storing it as a data-attribute on the button (similar to the nonce). There is a condition to check that this ID exists before rendering the button.

**Comment by dnaluz** [comment]
@kycapstick 

Another thing I just noticed, we need to pass the campaign id (relative to wordpress) to the endpoint because I will need to update meta data.  So lets update the campaign param to list and pass the campaign id as campaign

**Comment by kycapstick** [comment]
@dnaluz I've re-factored it so it pulls off the wordpress campaign id, and passes it through, but I didn't do anything with them in the campaign.php function as I wasn't sure where they should live. 

I pulled out the dummy button, but we will need to update the trigger in JS once the button is set up properly.

**Comment by kycapstick** [comment]
If we're using the same button for subscribe/unsubscribe, is the plan to change the class to "campaign__hero-cta--unsub" if the user is subscribed to the current campaign? We will need a way to trigger different calls depending.

**Comment by dnaluz** [comment]
> If we're using the same button for subscribe/unsubscribe, is the plan to change the class to "campaign__hero-cta--unsub" if the user is subscribed to the current campaign? We will need a way to trigger different calls depending.

We don't need to change the class.  But we may need to add a new acf field for the un subscribe button copy

**Comment by kycapstick** [comment]
> > If we're using the same button for subscribe/unsubscribe, is the plan to change the class to "campaign__hero-cta--unsub" if the user is subscribed to the current campaign? We will need a way to trigger different calls depending.
> 
> We don't need to change the class. But we may need to add a new acf field for the un subscribe button copy

If we're not changing the class, do we have another way to know which ajax call to make?

**Comment by dnaluz** [comment]
@kycapstick 

You're right, I have way of tracking and I'll make the necessary adjustments to the styles and js to make it work.

**Pull request merged**
