### PR TITLE
Feature/moz 74 event single

### PR DESCRIPTION
**Pull request by kycapstick**
This PR covers the event single page. 

Features:

- Event with image
- Event without image
- Physical location (with Map)
- Online location
- Events with 8 or less attendees
- Events with more than 8 attendees (display button to trigger lightbox)

Sidebar with that only displays the following if they're set: 

- External Link 
- Tags
- Campaign (using a placeholder value for the time being)

Share Button

- Triggers lightbox
- Only copy share link and Share to Twitter currently enabled

Related Events 
- Shows matching events by tag

### CODE REVIEW

**Comment by dnaluz** [comment]
@kycapstick You'll need to change the base of this PR, I tried but got an error.  We should try to be creating PRs against develop

**Comment by kycapstick** [comment]
@dnaluz your change must have taken because it's now showing that it's set to merge into develop

**Comment by dnaluz** [comment]
When I try to view an event I get this

Screen Shot 2019-11-08 at 12 21 12 PM

**Comment by kycapstick** [comment]
@dnaluz did my best to try and fix the bug, but I haven't been able to reproduce it in either my current set up or my vanilla WP setup. If it persists with this fix, let me know

**Comment by dnaluz** [comment]
@kycapstick, I found the issue you have the short open tag enabled on both your docker and native install of php / nginx.  This option is not always on and we should try to avoid the use of short open tags.

example:

`<? ?>` vs `<?php ?>`

We should always use the later way of opening php tags.  The issue was on ~340.  I made the fix.

**Comment by dnaluz** [comment]
The single event page seems to be missing some information doesn't quite match up with the figma file.
Screen Shot 2019-11-11 at 8 08 47 PM

**Comment by dnaluz** [comment]
When I edit an event the event image does not get loaded into it's appropriate field

**Comment by dnaluz** [comment]
When I click RSVP some messaging comes up.  
Screen Shot 2019-11-11 at 8 13 37 PM

**Comment by dnaluz** [comment]
Are we always showing who is hosting the event regardless if they are doing it through a group or not?

**Comment by dnaluz** [comment]
Missing related events

**Comment by dnaluz** [comment]
Missing attendees

**Comment by dnaluz** [comment]
Padding on the cards  in the right column should be 32px, currently closer to 50px

Screen Shot 2019-11-11 at 8 20 00 PM

**Comment by dnaluz** [comment]
Visited link colour shouldn't change

Screen Shot 2019-11-11 at 8 20 00 PM

**Comment by dnaluz** [comment]
Vertical spacing here looks off

Screen Shot 2019-11-11 at 8 23 27 PM

**Comment by dnaluz** [comment]
Avatar should also be part of the link to the member profile
Screen Shot 2019-11-11 at 8 25 04 PM

**Comment by dnaluz** [comment]
What is supposed to happen when you click report event?

**Comment by dnaluz** [comment]
The padding at the bottom of the page is off, should be 88px according to the figma file

Screen Shot 2019-11-11 at 8 27 14 PM

**Comment by dnaluz** [comment]
You'll need to apply the user visibility settings to the hosted by area.  It will only need to be done for the user profile image.  You can see how I implemented it in this PR 

https://github.com/mozilla/community-portal/pull/19.

**Comment by dnaluz** [comment]
The hero and form aren't lining up with the navigation on the edit event page

Screen Shot 2019-11-11 at 9 37 25 PM

**Pull request merged**
