### PR TITLE
Feature/moz 170 feature add additional fields to profile

### PR DESCRIPTION
**Pull request by dnaluz**
Added new fields to the member profile page.

- I have statically coded in the events information as I need to merge the event code in to make the proper connections but still wanted to get the appropriate styles in.

### CODE REVIEW

**Comment by dnaluz** [comment]
Added identicon to member members and navigation.

**Comment by kycapstick** [comment]
- Can't paste into bio
- Section titles should be font-weight normal (currently bold)
- Vertical alignment of section titles is off
Screen Shot 2019-11-08 at 4 13 35 PM

- Country and City inputs should be 50% each (right now City is wider)
- Hover state for checkbox is buggy if checked (hovering over checkbox proper)
- Changing Primary Information visibility settings does not change the setting on profile photo
- Communication & Interests visibility settings does not change the setting on Languages Spoken
- Add Another Language button shouldn't have the text-decoration: underline
- All language inputs should be in-line. Right now the first one is full width.
- Horizontal divider missing between Email contact and Phone contact
- Text on Complete Profile button shouldn't be all uppercase

Notes on the Single Member page:

- Social handles grid is broken
- Edit button has changed
- Fonts for username, name and pronouns looks off
- Should groups and events link out to those items?

**Comment by dnaluz** [comment]
> Add Another Language button shouldn't have the text-decoration: underline

In the figma file I have there is an underline
Screen Shot 2019-11-08 at 5 33 21 PM

**Comment by dnaluz** [comment]
Fixed paste bug for bio field

**Comment by dnaluz** [comment]
Changed font weight to normal

**Comment by dnaluz** [comment]
Vertical align section titles

**Comment by dnaluz** [comment]
Added keyline between phone and email

**Comment by dnaluz** [comment]
removed touppercase on CTA

**Comment by dnaluz** [comment]
> Communication & Interests visibility settings does not change the setting on Languages Spoken

This works for me.  Have a screen capture of it working but github won't let me upload a video.

**Comment by dnaluz** [comment]
Lined up select boxes for languages

Screen Shot 2019-11-11 at 10 01 14 AM

**Comment by dnaluz** [comment]
Country and City now half 

Screen Shot 2019-11-11 at 2 44 34 PM

**Comment by dnaluz** [comment]
Placed a min width on the social icons for smaller desktop. Now if the column gets to small it will stack all of the items instead of one at at time.

**Comment by dnaluz** [comment]
Updated edit icon

**Comment by dnaluz** [comment]
Fixed email overflow

**Pull request merged**
