### PR TITLE
Fix/moz 233 event single fixes

### PR DESCRIPTION
**Pull request by kycapstick**
This PR will:

- Add in fix to verify URL for both online meeting links and external URLs and only render HTML elements if URLs are valid. 
- Fixed responsive styling bugs 
- Allow for multiple admins

### CODE REVIEW

**Comment by dnaluz** [comment]
Multiple admins for what?

**Comment by kycapstick** [comment]
@dnaluz events hosted by groups with multiple admins

**Comment by dnaluz** [comment]
Oh where the event displays the group admins

Looks like it's still not lining up properly

Screen Shot 2019-11-19 at 1 23 38 PM

**Comment by kycapstick** [comment]
Checked with Ahmed and he said in that situation to center the share button vertically when it's in that position. Change has been committed alongside a small styling bug in the cancel button on the edit event page and the share button when nothing else is populated.

**Comment by dnaluz** [comment]
Looks good now

**Pull request merged**
