### PR TITLE
Add nodemon to dependencies

### PR DESCRIPTION
**Pull request by MichaelKohler**
`npm run watch` is using nodeman:

```
"watch": "./node_modules/.bin/nodemon -e scss -x \"npm run build\"",
```

However this leads to the following error:

```
> community-portal@1.0.0 watch /home/mkohler/development/community-portal
> nodemon -e scss -x "npm run build"

sh: 1: nodemon: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! community-portal@1.0.0 watch: `nodemon -e scss -x "npm run build"`
npm ERR! spawn ENOENT
```

This is due to nodeman not being installed when running `npm install` or `npm ci`, as it's missing in the `devDependencies`. This PR adds it as dependency.

Output after installation:

```
> community-portal@1.0.0 watch /home/mkohler/development/community-portal
> nodemon -e scss -x "npm run build"

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: scss
[nodemon] starting `npm run build`

> community-portal@1.0.0 build /home/mkohler/development/community-portal
> npm-run-all compile prefix


> community-portal@1.0.0 compile /home/mkohler/development/community-portal
> node-sass scss/style.scss -o ./ --importer ./node_modules/node-sass-import

Rendering Complete, saving .css file...
Wrote CSS to /home/mkohler/development/community-portal/style.css

> community-portal@1.0.0 prefix /home/mkohler/development/community-portal
> postcss --use autoprefixer -b 'last 10 versions' style.css -o style.css

[nodemon] clean exit - waiting for changes before restart
```

### CODE REVIEW

**Comment by Mte90** [comment]
I guess that this pr is incomplete.

**Comment by MichaelKohler** [comment]
Why? What else would you need?

In any case, given how old this PR is, using a newer version of nodemon might be good.

**Comment by Mte90** [comment]
Well need to be integrated with the rest of the JS stuff and this pr just add on package.json

**Comment by MichaelKohler** [comment]
@Mte90 I've added a description to the PR, and updated nodemon to the latest version.

**Comment by Mte90** [comment]
My doubt where if it was also live reloading the page but as is just compiling the sass is not a problem.
Maybe add something in the readme about how to use it?

**Comment by MichaelKohler** [comment]
The README has a section, and I think that's enough. https://github.com/mozilla/community-portal#watch

What do you think?

**Comment by Mte90** [comment]
I missed it -.-'

**Pull request merged**
