### PR TITLE
Feature/security  events

### PR DESCRIPTION
**Pull request by kycapstick**

### CODE REVIEW

**Comment by kycapstick** [comment]
@jveens / @dnaluz not sure how you want to handle bugs for this, but here are a couple I've noticed:

- The title on single events isn't being echoed/printed. 
- The text is missing from "Results for" when a search term is applied
- Something in the event update functionality is breaking the RSVP functionality. It looks like it's not saving tickets to the event. RSVP worked for new events, and existing events, but if I update an event it breaks. 
- We might need to refactor the way filtering works. Right now we're defining the country and language options based on what's applied to the list of events pulled from the query. If they're applied, we're using country and tag(category) in that query so we're iterating through a limited list of events and that throws off the options for countries and languages. 
ie. if you select a country, it will limit the list of country options to the one you've selected or all. Similarly, if you select a tag it will limit the list of languages / countries to only those that have been applied to events with that tag. If there are no languages applied to any of those events, the language dropdown disappears, even if a language has been selected.

**Comment by dnaluz** [comment]
You're welcome to make these fixes, the work I did last week was strictly with creating and editing events.  I hadn't had a chance to look at the other parts of events.  The way filtering works should replicate how it works on production.  I don't think updating the coding standards has changed the way filtering work.

**Comment by dnaluz** [comment]
@kycapstick Fixed the title not being displayed.  It was happening across the site because the title wasn't being echoed.  Good find!

**Comment by dnaluz** [comment]
@kycapstick fixed the search value not being displayed

**Pull request merged**
