### PR TITLE
Fix/moz 231 pagination and permissions

### PR DESCRIPTION
**Pull request by kycapstick**
This PR will:

- Add pagination to the bottom of all Events pages views
- Update conditional rendering to remove the location icon if no country or city has been provided.

### CODE REVIEW

**Comment by dnaluz** [comment]
Pagination shouldn't show if there is only 1 page.

**Comment by dnaluz** [comment]
Looks like some styling issues are still present

Screen Shot 2019-11-19 at 1 25 07 PM

**Comment by dnaluz** [comment]
Looks good

**Comment by dnaluz** [comment]
Style issues still present

**Comment by kycapstick** [comment]
I thought this fix was for a different PR, I'm going to move it over to [#36 ] to make sure it meshes with other single event page styles

**Pull request merged**
