### PR TITLE
Feature/event localization urls

### PR DESCRIPTION
**Pull request by kycapstick**

### CODE REVIEW

**Comment by dnaluz** [comment]
@kycapstick 

Looks like that date issue is happening here for non english versions.  Probably because of strtotime as you mentioned before.

Screen Shot 2020-06-12 at 10 51 03 AM

**Comment by kycapstick** [comment]
Hey @dnaluz, I tested on both my setups in multiple languages and I can't replicate the issue.

**Comment by dnaluz** [comment]
It was happening when I edit an event in Spanish.

**Comment by kycapstick** [comment]
@dnaluz this has been updated so the selected tag is checked on the edit event page.

**Pull request merged**
