### PR TITLE
Feature/moz 72 events page

### PR DESCRIPTION
**Pull request by kycapstick**
This PR will: 

- Update create event link
- Fix horizontal spacing on events listing and create events page
- Fix create form validation functionality
- Update styling "Edit event location" on create event page

### CODE REVIEW

**Comment by kycapstick** [comment]
To get create event link to work you'll need to create a page called "Edit Event" that is a child of the "Events" page. Then in the Events Manager settings for Edit events page, under pages, select the "Edit Event" page. 

For the tags I'm leveraging the "Categories"attribute that's built into Events Manager. They don't need to be added to an event to display, but they do need to be added in the backend under Events Categories. 

Screen Shot 2019-10-30 at 4 48 07 PM

I've added a fallback so the filter is still populated with the full list if no categories are defined on the backend.

**Comment by dnaluz** [comment]
@ky can we leverage the normal Wordpress tags for the events instead of the ones used specifically for EventsManager.  Groups and Members are using the regular wordpress tags to handle this.  The Mozilla team shouldn't need to manage two separate taxonomies in the case they need to add a new one.

**Comment by kycapstick** [comment]
@dnaluz I assume yes, but it would mean I would have to re-do all logic related to the tagging (filtering for all four views, event cards, event creation, and single event) as those are all pulling from the classes in Event Manager. We can discuss tomorrow if you'd like.

**Comment by dnaluz** [comment]
@kycapstick 

Screen Shot 2019-11-05 at 2 29 01 PM

Added the Edit event page the create event page still does not show up

**Comment by kycapstick** [comment]
Not sure @dnaluz, I set it up the same way in my standard install and it seems to be working fine. I've reset all the settings so it shouldn't be any setting I've changed. We can take a look today

**Comment by dnaluz** [comment]
@kycapstick 

So I figured out what the issue is with the pages not showing.  Events manager is setup to use the page hierarchy from wordpress.  When you create the "Edit Event" page in wordpress you have to make sure that the slug matches what you have hard coded in your Events page header.  In my case my slug for the page was 'edit-event' since that your instructions were to create a page called a'Edit Event'.  Wordpress automatically takes the title and creates a slug based off that, the link you have on your Events page is /create-event/.  I'm not sure if there is a better way to handle this within Event Manager.  We should definitely document this though going forward.

**Comment by dnaluz** [comment]
Screen Shot 2019-11-08 at 3 30 15 PM

The hero section should not move pass the left edge of the navigation menu.  This was a visual bug I had introduced in my previous pages, I have fixed the issue in https://github.com/mozilla/community-portal/pull/16

**Comment by dnaluz** [comment]
I am getting javascript errors not sure if there is some configuration I need to do?

Screen Shot 2019-11-08 at 3 32 09 PM

**Comment by dnaluz** [comment]
Styling needs to be applied here
Screen Shot 2019-11-08 at 3 32 58 PM

**Comment by dnaluz** [comment]
Are we styling the calendars?  
Screen Shot 2019-11-08 at 3 33 33 PM

**Comment by dnaluz** [comment]
You should change the mouse to a pointer on hover for the create event button

**Comment by dnaluz** [comment]
If there is an error I should be moved to the field that is missing

**Comment by dnaluz** [comment]
Screen Shot 2019-11-08 at 3 38 04 PM

We should stick to the error conventions we are using for groups and members when a user does not check the consent box

**Comment by dnaluz** [comment]
I have the checkbox for consent checked but it still won't allow me to create an event

**Comment by dnaluz** [comment]
When the page comes back with an error the image I uploaded is gone from dropzone.

**Comment by dnaluz** [comment]
Added a tag through event manager and it did not show up.

**Comment by kycapstick** [comment]
Hey @dnaluz 

I've pushed changes for most of these, but there are two Events Manager settings that need to be updated. 

Disable Google Maps 
- In general tab under Google Maps and Location Services set "Enable Google Maps integration?" to "no"

Turn Off Data Collection
- In the General tab under Privacy change all the options that are "Include All" by default to "Do Not Include"

Screen Shot 2019-11-11 at 3 52 08 PM

The following changes have been actioned:

- Stop hero from overflowing on Edit/Create Event Page
- Update functionality and style dropzone
- Change cursor to pointer on hover of button
- Have screen scroll to input in error state upon submission

**Comment by dnaluz** [comment]
Nothing major but fields with an error state shouldn't have the labels change colour to red, just the outline on the field and the error message.

Screen Shot 2019-11-11 at 3 59 00 PM

**Comment by dnaluz** [comment]
Let's look at trying to remove the powered by events manager copy and link at the bottom of the pages.

**Comment by dnaluz** [comment]
One last thing, the event tags still aren't showing I have defined both event manager tags and wordpress tags.

After these fixes are done we are good to merge this into develop!

**Comment by dnaluz** [comment]
@kycapstick I've gone ahead and added styles to remove the powered by Events Manager

**Comment by dnaluz** [comment]
I've gone ahead and removed the error class from the labels

**Comment by dnaluz** [comment]
I think the only major issue with this PR is the missing tags.  Once that's good we should be good to merge

**Comment by dnaluz** [comment]
There should be a transition on hover effect for the tags.

`
transition: all 0.3s ease-in;
`

Is what i have set for the tags in create group

**Comment by dnaluz** [comment]
I've gone ahead and added the transition

**Comment by dnaluz** [comment]
Just noticed this but the event cards do not line up with the filters and the filters do not line up with the navigation / hero.

Screen Shot 2019-11-11 at 9 32 20 PM

**Comment by kycapstick** [comment]
@dnaluz sorry about that. Accidentally removed that line. Also pulled out the fix for the "Powered By Events Manger" badge as it was breaking styles on the events page. We can remove that badge in the settings. At the bottom of the general settings is one called "Show Some Love" which we can set to "no"

**Comment by dnaluz** [comment]
This looks like it's in a decent spot to merge into development!

**Pull request merged**
