### PR TITLE
Add docker-compose

### PR DESCRIPTION
**Pull request by MichaelKohler**
This adds a docker-compose file to set up Wordpress and instructions on how to set up the instance.

However, when running this, the CSS does not get properly applied for everything, is there something that additionally needs to be done? I don't see any obvious errors in the dev tools console (apart from the font being blocked by Firefox for my case, but that shouldn't matter too much).

Screenshot 2019-11-02 at 17 56 17

### CODE REVIEW

**Comment by asdofindia** [comment]
Members page seems to work fine.
image

**Comment by MichaelKohler** [comment]
Apart from the footer and the top navigation.

**Comment by dnaluz** [comment]
There are quite a bit of changes coming into the repo.  Once everything is merged we will update the readme on how to get everything up and running.  We have moved away from using docker however because it was interfering with the auth0 plugin implementation.  Currently I'm developing with nginx / php / mysql on my native system.

**Comment by couci** [comment]
@MichaelKohler is that still needed?

**Comment by MichaelKohler** [comment]
I guess this would need to be updated. I think this would still be beneficial for developer experience. I'm closing this for now, a new version should also take care of setting up WordPress as we need it.

**Pull request closed without merging**
