### PR TITLE
Feature/moz 187 edit group age

### PR DESCRIPTION
**Pull request by dnaluz**
Was finally able to keep this PR somewhat small yay!  Some design may be broken but they should be fixed in other PRs.  We may run into some conflicts as we merge these PRs but I don't think it will be a major issue.

Added group edit page.  I believe there are some outstanding PRs that link to this page so if you already have a group created you can hit the group edit link by visiting

/groups/SLUG/admin/edit-details/

Where slug is the slug of the group.  You should try to test editing the group as a group admin and  as a non admin for the group.  I also had to restructure how dropzone worked in both the create a group and edit group pages, both should be working fine now.  We may need to ask design about perhaps designing no access pages.

### CODE REVIEW

**Comment by kycapstick** [comment]
- Can't paste into bio
- Section titles should be font-weight normal (currently bold)
- Vertical alignment of section titles is off
Screen Shot 2019-11-08 at 4 13 35 PM

- Country and City inputs should be 50% each (right now City is wider)
- Hover state for checkbox is buggy if checked (hovering over checkbox proper)
- Changing Primary Information visibility settings does not change the setting on profile photo
- Communication & Interests visibility settings does not change the setting on Languages Spoken
- Add Another Language button shouldn't have the text-decoration: underline
- All language inputs should be in-line. Right now the first one is full width.
- Horizontal divider missing between Email contact and Phone contact
- Text on Complete Profile button shouldn't be all uppercase

**Comment by dnaluz** [comment]
@kycapstick 

This is the edit group page, are you posting these issues on the wrong PR?

**Comment by kycapstick** [comment]
@dnaluz yep! Sorry! Realized and moved my feedback to the right PR

**Comment by kycapstick** [comment]
The page seems to be working as expected. The styling does break below desktop, but I assume a lot of that will be fixed in the other PRs. So this one should be good to go!

**Pull request merged**
