### PR TITLE
Feature/moz 388 members language filter

### PR DESCRIPTION
**Pull request by dnaluz**
This adds language as a dimension to search by for members.  Please check if all combinations work.  A combination of all 4 of the filters, 3 different filters, 2 different filters and each individual filter.

Adding this fourth dimension to search by added a lot of new combinations that need to be verified!

### CODE REVIEW

**Comment by dnaluz** [comment]
> This looks good, only thing I noticed is that if no member has a language set and set to public or registered users the language filter doesn't show up at all. Once one is set everything works just fine.

Yeah, thats intended if no languages are set it doesn't display the filter because it's only displaying languages that are being used by members.

**Comment by kycapstick** [comment]
Should we be doing the same for countries? Right now it's showing up if no countries are set.

**Comment by dnaluz** [comment]
> Should we be doing the same for countries? Right now it's showing up if no countries are set.

On production this isn't an issue because there are countries already set and it only shows countries being used.  This is a stop gap because it is a new field and we don't want to show an empty list of languages.

**Comment by kycapstick** [comment]
In that case, this is good to go!

**Pull request merged**
