### PR TITLE
Feature/moz 76 groups main

### PR DESCRIPTION
**Pull request by dnaluz**
Ahh so I did it again and included too many changes within a PR.  

I Updated the Hero areas for
- Members
- Members Edit Profile
- Groups
- Create Group

Updated the structure of the Create Group Form, was not happy with the original structure and how it responded to resizing the screen.

 On to the main points of this PR

- The groups main page found @ /groups/
Please test all the filters and search (Groups I'm in, Text search, Location search and Tags).  Also create enough groups to test the responsive nature of the page along with paging.   Should probably make a few groups with different tags, locations etc to test.

I apologize again for this monstrosity of a PR.

### CODE REVIEW

**Comment by kycapstick** [comment]
**Hero on Members Page**

- Padding between green dot and title is currently 8px, should be 14px
- Line-height on header paragraph is 24px should be 28px

**Hero on Members Edit Page**

- Bakground image overlaps with text around 1300px
- Color of disabled select is too light (should be $color-gray-secondary)

**Hero on Groups** 

- Create a group link is missing the right chevron
- Padding between green dot and title is currently 8px, should be 14px
- Line-height on header paragraph is 24px should be 28px

**Hero on Create Groups**

- Create group hero section should be a bit taller
- The create group menu (1. Basic Info, 2. T& R, etc) is missing on mobile

**Create Group Form** 

- Custom radio button doesn't match current design
- For the image upload missing the min dimensions 
- Group image input drops to it's own line but doesn't spread to full width at 768px
- It looks like copy on the Groups creation page has been updated.
- Text in Continue button shouldn't be capitalized, not uppercase
- Whenever I try a group name I get the this group name is already taken error for that name. 
- If I ignore this error and click "continue" a second time it takes me to the success screen
- I can't paste into any inputs
- Tooltip added to Secondary Group contact
- Line height of the Community Guidelines text and the checkbox label should be increased to 24px
- There are a few copy updates, but it probably makes more sense to leave those until the copywriter does their thing

**Groups Main**

- Search icon is out of alignment with search text
- Search placeholder should read "Search groups"
- Missing the light gray divider on top of filtering
- Labels for filters (Location and Tags) shouldn't have semicolons
- Discover Groups and Groups I'm In should both be 14px (both are currently 16px)
- Cards missing hover state
- Missing zero state
- If I select a Tag or Location and then set it back to All, no events show up (even if there are events)
- There is extra whitespace before the comma between City and Country on cards
- There is no white space between number of members and the word "members"
- Pagination isn't showing up at all for me. Page will cap out at 12 groups, but pagination doesn't show up.

**Comment by dnaluz** [comment]
Adjusted spacing between dot and title on members page

**Comment by dnaluz** [comment]
Adjusted line height on members page hero area from 24 to 28

**Comment by dnaluz** [comment]
- Updated copy on profile edit page and fixed overlapping of the hero image on the text
- Added missing chevron to groups hero area create group link
- Adjusted horizontal spacing between title and dot on groups hero area
- Adjusted hero copy line height on groups page
- Adjusted colour of disabled select on members edit page
- Adjusted height on hero area for create group
- I added a task to create a menu for mobile in create group to keep it separate from this PR because it will require more coding
- Updated radio button styles
- Removed upper case of continue button
- Added min dimensions for image and styles.
- Full width group image at mobile
- All copy across the site will be updated so lets ignore those differences
- The bug where the group name validation has been fixed in a different PR
- Fixed bug with paste being disabled
- Added tooltip icon, but using placeholder copy for now until we get it from mozilla.
- Adjusted search icon position on groups page
- Updated placeholder for search groups 
- Added missing border above filtering
- Updated tags and location copy
- Updated menu font size to 14px
- Removed extra white space between country and city
- Added white space between member count
- Fixed location and tag reset filter bug

**Comment by kycapstick** [comment]
@dnaluz 
This is all looking great! A couple of bugs: 

- I added more than 12 groups but the Discover Groups page is only showing me 12 and no pagination. 
- On the Groups I'm In view it's showing all 19 groups I've created, as well as pagination links on the bottom that don't seem to work when I click them. 
- The outline of where you are is still missing from the header of the Create Group page on tablet and mobile. 

Screen Shot 2019-11-08 at 1 43 49 PM

**Comment by dnaluz** [comment]
Fixed pagination bug where it was not showing

**Comment by dnaluz** [comment]
Fixed groups I'm in filter bug

**Comment by dnaluz** [comment]
For the 

> The outline of where you are is still missing from the header of the Create Group page on tablet and mobile.

I have created a new ticket.  It is going to require a bit more coding and wanted to keep it out of this PR.  New Jira ticket for this can be found https://playgroundinc.atlassian.net/jira/software/projects/MOZ/boards/18?selectedIssue=MOZ-184

**Comment by dnaluz** [comment]
Added mobile menu for create group

**Comment by dnaluz** [comment]
Found another bug causing pagination to break, has now been fixed

**Comment by dnaluz** [comment]
Fixed a bug with the my groups filter not working correctly

**Comment by dnaluz** [comment]
> * Group cards are missing hover state

I've decided to keep the hover state on the cards out to see which the mozilla team likes better.  We can make a separate issue for this

> * On tablet/mobile if I try and toggle to Terms & Responsibilities and then back to Basic Information it throws a "this field is required error" on that select.

Removed error message

**Comment by dnaluz** [comment]
> * Zero state
> * The "results for" text when using search

Added

**Pull request merged**
