### PR TITLE
Bug/moz 316 keyboard navigation

### PR DESCRIPTION
**Pull request by kycapstick**
Sorry that this PR got a bit larger than anticipated. Wanted to update accessibility in a couple of places. 

- Should be able to tab through all cards 

Many of the elements that needed to be updated were used in Events, Groups and Member creation/editing. The following elements have been updated across all three:

- CPG checkbox
- Tags selection
- Dropzone image upload

In Groups:

- Updated custom radio buttons

In Events

- Updated rendering of labels to fix alignment issues.

### CODE REVIEW

**Comment by dnaluz** [comment]
Thanks for this.  Will review it once I'm done the campaigns listing page.

**Comment by kycapstick** [comment]
Thanks @dnaluz, should be fixed now!

**Comment by dnaluz** [comment]
@kycapstick.  Interesting bug here with dropzone and submitting the form.  So navigating to the drop zone element works fine now, but to activate the file upload popup you need to press enter.  Upon pressing the enter key it submits the form at the same time.  We should probably disable submitting the form through the enter key until we've hit the submit button.  Unless we can think of a different approach?

**Comment by kycapstick** [comment]
Good call @dnaluz! I didn't catch this as I was using the spacebar to trigger the upload functionality, which also works. From what I've since read it's best practice in accessibility not to mess with the implicit submit functionality of the enter key, as keyboard users expect it to be available. I assume they would also know to use the spacebar in this situation.

**Comment by dnaluz** [comment]
@kycapstick then the enter for triggering the dropzone upload popup should be disabled.  If the default for submitting a form is the enter key it should not trigger the dropzone action.

**Comment by kycapstick** [comment]
Sounds good! I've moved the dropzone scripts to their own file and updated the functionality to better support keyboard users.

**Comment by dnaluz** [comment]
@kycapstick We're almost there with this PR.  There is one more little thing we can fix.  When using the keyboard to navigate the edit / create group form and there is an image already uploaded and you hit space bar to remove the image you lose focus, perhaps we can put focus back on the dropzone element so they can re upload an image instead of having to tab through all the previous elements.

**Comment by kycapstick** [comment]
Great point! I've pushed this change.

**Comment by dnaluz** [comment]
This looks good

**Pull request merged**
