### PR TITLE
Feature/security  groups

### PR DESCRIPTION
**Pull request by dnaluz**
Updates to pass phpcs Wordpress standard for the groups section of the site.  

There are some warnings that have been tracked in the PHPCS spread sheet.  Please test all of the group section.  Creating a group, updating a group, viewing a group.  Also test verifying and un-verifying in the back end.  I've also updated how images are uploaded so we'll need to test all the different image uploading areas (groups, members, events) of the community side of the site.

### CODE REVIEW

**Comment by jveens** [comment]
"Events this month" heading should only show if there are events to show.
Screen Shot 2020-04-30 at 4 59 39 PM

**Comment by jveens** [comment]
Members totals for groups are being calculated, but the 'Our Members' tab only shows Admin Contacts.
Screen Shot 2020-04-30 at 5 04 55 PM
Screen Shot 2020-04-30 at 5 05 04 PM

**Comment by jveens** [comment]
'Meeting Details' heading should only show if there are details to display
Screen Shot 2020-04-30 at 5 08 55 PM

**Comment by jveens** [comment]
Tags in groups are displayed using the tag slug instead of the tag label.
Screen Shot 2020-04-30 at 5 13 01 PM
Screen Shot 2020-04-30 at 5 13 13 PM

**Comment by dnaluz** [comment]
> Tags in groups are displayed using the tag slug instead of the tag label.
> Screen Shot 2020-04-30 at 5 13 01 PM
> Screen Shot 2020-04-30 at 5 13 13 PM

@jveens this has been fixed

**Comment by dnaluz** [comment]
> 'Meeting Details' heading should only show if there are details to display
> Screen Shot 2020-04-30 at 5 08 55 PM

@jveens this has been fixed

**Comment by dnaluz** [comment]
> Members totals for groups are being calculated, but the 'Our Members' tab only shows Admin Contacts.
> Screen Shot 2020-04-30 at 5 04 55 PM
> Screen Shot 2020-04-30 at 5 05 04 PM

@jveens this has been fixed

**Comment by dnaluz** [comment]
> "Events this month" heading should only show if there are events to show.
> Screen Shot 2020-04-30 at 4 59 39 PM

@jveens this has been fixed

**Comment by jveens** [comment]
It looks like the tags show up on the front of the group cards, but they are still displaying the tag slug instead of the tag label on the Group page.
Screen Shot 2020-05-01 at 10 37 53 AM

Also, when I was first testing slug vs label, I had changed the slug for one of the tags, and it looks like there are some complications with that as well - There should only be 2 tags on this group, and from the card view, as well as the group single view, you can see that it is listing 3 as a result of that change.
Screen Shot 2020-05-01 at 10 38 41 AM

**Comment by jveens** [comment]
> > 'Meeting Details' heading should only show if there are details to display
> > Screen Shot 2020-04-30 at 5 08 55 PM
> 
> @jveens this has been fixed

@dnaluz I pulled your changes, and I am still seeing this for existing groups, and when creating new ones

**Comment by dnaluz** [comment]
@jveens changing slugs will do that as the buddy press doesn't handle tags in a one to one manner with regards to wordpress and groups is uses the slug as meta data to associate with the group.  This type of situation wouldn't happen on production as the old tags setup are set in stone and won't be modified because of the issue you mentioned.  Ideally tag ids are stored with the group but we can't go that route without having to update all groups and converting the tag system.

**Comment by jveens** [comment]
> "Events this month" heading should only show if there are events to show.
> Screen Shot 2020-04-30 at 4 59 39 PM

👍

**Comment by dnaluz** [comment]
@jveens Didn't know it was happening on the group detail page as well with regards to tags.  Should be fixed now

**Comment by jveens** [comment]
> > > 'Meeting Details' heading should only show if there are details to display
> > > Screen Shot 2020-04-30 at 5 08 55 PM
> > 
> > 
> > @jveens this has been fixed
> 
> @dnaluz I pulled your changes, and I am still seeing this for existing groups, and when creating new ones

@dnaluz This issue is resolved now! 👍

**Pull request merged**
