### PR TITLE
Feature/security  campaigns

### PR DESCRIPTION
**Pull request by kycapstick**
Updated the following files to implement code sniffer standards:

page-campaigns.php 
single-campaign.php

For the sake of keeping this PR to a reasonable size, all campaign blocks and the newsletter will be handled on their own PRs.

### CODE REVIEW

**Comment by dnaluz** [comment]
Markup is being escaped on the campaigns listing page

Screen Shot 2020-04-20 at 12 21 04 PM

You will need to implement something similar to what I have on the members profile page

`	echo wp_kses(
					wpautop( substr( trim( $string ), 0, 3000 ) ),
					array(
						'p'  => array(),
						'br' => array(),
					)
				);`

This will allow breaks and paragraph tags to be used and everything else is escaped.  I suggest you go look at what they have in production in this area, Im not sure if they include links and other tags.

**Comment by dnaluz** [comment]
Same thing on the single campaign page

Screen Shot 2020-04-20 at 12 24 18 PM

**Comment by dnaluz** [comment]
@kycapstick 

> Markup is being escaped on the campaigns listing page
> 
> Screen Shot 2020-04-20 at 12 21 04 PM
> 
> You will need to implement something similar to what I have on the members profile page
> 
> ` echo wp_kses( wpautop( substr( trim( $string ), 0, 3000 ) ), array( 'p' => array(), 'br' => array(), ) );`
> 
> This will allow breaks and paragraph tags to be used and everything else is escaped. I suggest you go look at what they have in production in this area, Im not sure if they include links and other tags.

**Comment by dnaluz** [comment]
@kycapstick 

Same thing on the single campaign page

Screen Shot 2020-04-20 at 12 24 18 PM

**Comment by kycapstick** [comment]
@dnaluz fixed and added a similar fix to the descriptions on campaign cards.

**Comment by dnaluz** [comment]
@kycapstick still some errors here

Screen Shot 2020-04-20 at 5 06 48 PM

**Comment by kycapstick** [comment]
Thanks @dnaluz! I forgot to run phpcbf again after the latest fixes. Should be good to go now

**Comment by dnaluz** [comment]
@kycapstick Sorry, I missed something here.  I think we should add links and a corresponding class attribute as allowed markup in wp_kses calls.

**Comment by kycapstick** [comment]
This branch now pulls together all the updates to the Campaigns related files.

In the root folder: 

page-campaigns.php
single-campaign.php
page-newsletter.php

In ./lib 

campaigns.php

In ./templates

campaign-rsvp.php
campaigns-newsletter.php
newsletter-form.php

All files in ./templates/blocks

**For Testing**

When testing the newsletter signup form you can use the test emails to test for success state and failure state:

success@example.com 
failure@example.com

Need to test full campaigns page, single campaigns page (with all blocks), and newsletter page (You may need to create a page called "newsletter").

**Comment by dnaluz** [comment]
@kycapstick could we test this one more time.  I just did a big merge to resolve some conflicts with the base.  Want to make sure this is still in good standing.

**Pull request merged**
