### PR TITLE
Added hover and focus states to buttons

### PR DESCRIPTION
**Pull request by dnaluz**
Added hover/focus states to buttons.

### CODE REVIEW

**Comment by kycapstick** [comment]
This looks great! Only thing I noticed is that the edit button on the single events page have a square blue border, a similar thing happens on the remove image button on the edit event page.

**Comment by dnaluz** [comment]
> Looks great! Only thing I noticed was that the edit button on single events has a blue border and the remove image button on the events editor page.

**Comment by dnaluz** [comment]
@kycapstick great catches.  I pushed fixes!

**Comment by kycapstick** [comment]
This looks great!

**Pull request merged**
