### PR TITLE
Translations/match all spanish

### PR DESCRIPTION
**Pull request by kycapstick**
Pulled in translations provided by Senior and fixed a couple of bugs in the events translations.

### CODE REVIEW

**Comment by dnaluz** [comment]
@kycapstick 

It's displaying english version on the profile detail page of whether a group is an online group or not

Screen Shot 2020-06-23 at 1 08 49 PM

**Comment by dnaluz** [comment]
> @kycapstick
> 
> It's displaying english version on the profile detail page of whether a group is an online group or not
> 
> Screen Shot 2020-06-23 at 1 08 49 PM

I've fixed this issue

**Comment by dnaluz** [comment]
> Do we need to translate a user's languages?
> Screen Shot 2020-06-24 at 4 01 24 PM

Countries and languages haven't been translated yet in the po files so they're falling back to english.

**Comment by jveens** [comment]
> > Do we need to translate a user's languages?
> > Screen Shot 2020-06-24 at 4 01 24 PM
> 
> Countries and languages haven't been translated yet in the po files so they're falling back to english.

Alright great! I'm going to merge this in then.

**Pull request merged**
