### PR TITLE
Feature/translation urls groups

### PR DESCRIPTION
**Pull request by dnaluz**
This includes the updated URLs for the groups section.

To test you'll need to add the language code to the URL before groups example

/groups/

should be

/es/groups/

you should be able to click around and create and edit groups while staying in that particular translation (minus the main menus).

### CODE REVIEW

**Comment by dnaluz** [comment]
@kycapstick @jveens lets re test this across the board this now has all other PRs merged.

**Comment by dnaluz** [comment]
@jveens @kycapstick ok everything is merged into this PR lets retest and see if there are any bugs in the redirects or language switching for all sections.

**Comment by kycapstick** [comment]
Everything looks good to me!

**Comment by jveens** [comment]
@dnaluz I can log in, but I can't log out

Screen Shot 2020-06-22 at 1 08 02 PM

**Comment by dnaluz** [comment]
> @dnaluz I can log in, but I can't log out
> 
> Screen Shot 2020-06-22 at 1 08 02 PM

Logging out doesn't work on develop either, there is a setting in auth0 that isn't set properly.  I'm using mozilla's auth0 so I can't change the setting.

**Pull request merged**
